name = "lbc-pc-analyzer-api"
main = "src/index.ts"
compatibility_date = "2026-06-15"
workers_dev = false
preview_urls = false
routes = [{ pattern = "pc-analyzer-api.plaw.fr", custom_domain = true }]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "lbc_pc"
database_id = "50760761-f9fd-4088-86c8-b23d33bca3f5"
